// <auto-generated />
using System;
using EntityFrameworkCoreDemo.CodeFirst;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntityFrameworkCoreDemo.CodeFirst.Migrations
{
    [DbContext(typeof(EFCoreDemoContext))]
    partial class EFCoreDemoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityFrameworkCoreDemo.CodeFirst.DomainEntities.Gender", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("ID");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.ToTable("Gender");

                    b.HasData(
                        new
                        {
                            ID = new Guid("f093de04-28cf-4e10-82a8-b711e5b40da3"),
                            Code = "F",
                            Name = "Female"
                        },
                        new
                        {
                            ID = new Guid("dd33c96a-8152-4266-9cbb-111af45befe9"),
                            Code = "M",
                            Name = "Male"
                        },
                        new
                        {
                            ID = new Guid("3b8b18c5-d28a-43b3-a095-da15db73b668"),
                            Code = "U",
                            Name = "Unknown"
                        });
                });

            modelBuilder.Entity("EntityFrameworkCoreDemo.CodeFirst.DomainEntities.Person", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<Guid?>("GenderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("ID");

                    b.HasIndex("GenderID");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("EntityFrameworkCoreDemo.CodeFirst.DomainEntities.Person", b =>
                {
                    b.HasOne("EntityFrameworkCoreDemo.CodeFirst.DomainEntities.Gender", "Gender")
                        .WithMany("Persons")
                        .HasForeignKey("GenderID");
                });
#pragma warning restore 612, 618
        }
    }
}
